spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.191.118:3306/learning?characterEncoding=UTF-8&user=root&password=Mwp@123&failOverReadOnly=false&secondsBeforeRetryMaster=0&queriesBeforeRetryMaster=0&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&connectTimeout=30000&socketTimeout=30000
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 30000
      minimum-idle: 5

#驼峰命名转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
